package com.tyss.frozenbottleapi.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.tyss.frozenbottleapi.entity.FoodOrder;

public interface FoodOrderRepository extends JpaRepository<FoodOrder, Integer>{
	//Query will be generated by the repository
	List<FoodOrder> findByStatus(String status);
	
	//Custom query
	@Query("select u.orders from User u where u.id=?1")
	List<FoodOrder> findFoodOrderByUserId(int id);
}
